version: "3.9"

services:
  backend:
    build:
      context: ./backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: smart_lost_and_found
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:16
    container_name: smart-lost-and-found-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_lost_and_found
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
